version: '3'
services:
  webkitabfackeln:
    container_name: webkit_abfackeln
    build: .
    volumes:
      - '../webkit:/app/webkit'
    ports:
      - "127.0.0.1:8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: webkit_elasticsearch
    ports: ['127.0.0.1:9200:9200']
    volumes:
      - '../elastic:/usr/share/elasticsearch/data'
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - 'ELASTIC_PASSWORD=unsecure'
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: webkit_kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=unsecure
    ports: ['127.0.0.1:5601:5601']
    depends_on:
      - elasticsearch
